networks:
  pg-network:

    

services:
  pg-database:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - D:/coding/project/project_study/Project_DE/01-docker-teraform/2_docker_sql/ny_taxi_postgres_data_2/:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "ny_taxi"]
    #   interval: 5s
    #   retries: 5
    ports:
      - 5432:5432
    restart: always
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root 
    ports:
      - 8080:80
    networks:
      - pg-network

# docker run -it \
#   -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#   -e PGADMIN_DEFAULT_PASSWORD="root" \
#   -p 8080:80 \
#   dpage/pgadmin4  